server:
  port: 7030
spring:
  application:
    name: gataway-server
  http:
    multipart:
      location: /temp

  profiles:
    active: @profile-active@

  redis:
    host: 10.0.8.199
    port: 6379

  zipkin:
    kafka:
      topic: zipkin

  kafka:
    bootstrap-servers: 10.0.8.199:9092


  sleuth:
    sampler:
      percentage: 1.0

zuul:
  ribbon:
  ignoredServices: '*'
  sensitive-headers: Cookie,Set-Cookie
  ratelimit:
    key-prefix: zuul-ratelimite
    enabled: true
    repository: redis
    default-policy-list:
      - limit: 50
        quota: 5
        refresh-interval: 5
        type:
          - user
    policies:
      io-server:
        limit: 10
        quota: 1000
        refresh-interval: 10
        type:
          - user

management:
  security:
    enabled: false

hystrix:
  command:
    io-server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 70000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ReadTimeout: 4000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 2000


io-server:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 2000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    ServerListRefreshInterval: 2000